#############################################################################
# Makefile for building: TorrentUploader
# Generated by qmake (2.01a) (Qt 4.5.2) on: ?? 27. ??? 11:19:14 2009
# Project:  TorrentUploader.pro
# Template: subdirs
# Command: c:\Develop\Qt\2009.03.1\qt\bin\qmake.exe -spec c:\Develop\Qt\2009.03.1\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o Makefile TorrentUploader.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\Develop\Qt\2009.03.1\qt\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-src

src\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) src.pro -spec c:\Develop\Qt\2009.03.1\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) src.pro -spec c:\Develop\Qt\2009.03.1\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-src: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: TorrentUploader.pro  c:/Develop/Qt/2009.03.1/qt/mkspecs/win32-g++/qmake.conf c:/Develop/Qt/2009.03.1/qt/mkspecs/qconfig.pri \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/qt_functions.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/qt_config.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/exclusive_builds.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/default_pre.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/win32/default_pre.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/release.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/debug_and_release.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/default_post.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/win32/default_post.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/win32/rtti.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/win32/exceptions.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/win32/stl.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/shared.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/warn_on.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/qt.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/win32/thread.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/moc.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/win32/windows.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/resources.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/uic.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/yacc.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/lex.prf \
		c:/Develop/Qt/2009.03.1/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec c:\Develop\Qt\2009.03.1\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o Makefile TorrentUploader.pro
c:\Develop\Qt\2009.03.1\qt\mkspecs\qconfig.pri:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\qt_functions.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\qt_config.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\exclusive_builds.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\default_pre.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\win32\default_pre.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\release.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\debug_and_release.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\default_post.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\win32\default_post.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\win32\rtti.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\win32\exceptions.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\win32\stl.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\shared.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\warn_on.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\qt.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\win32\thread.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\moc.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\win32\windows.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\resources.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\uic.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\yacc.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\lex.prf:
c:\Develop\Qt\2009.03.1\qt\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Develop\Qt\2009.03.1\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o Makefile TorrentUploader.pro

qmake_all: sub-src-qmake_all FORCE

make_default: sub-src-make_default FORCE
make_first: sub-src-make_first FORCE
all: sub-src-all FORCE
clean: sub-src-clean FORCE
distclean: sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

sub-src-sub_Debug: src\$(MAKEFILE)
	cd src\ && $(MAKE) debug
debug: sub-src-sub_Debug

sub-src-sub_Release: src\$(MAKEFILE)
	cd src\ && $(MAKE) release
release: sub-src-sub_Release

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

